# Proprietes de l'application
spring:
  application:
    name: acactionneurs
  profiles:
    active: dev
  # Adresse du service de configuration
  config:
    import: optional:configserver:http://localhost:10002